# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
<<<<<<< HEAD
_commit: 0.5.1
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: your@email.tld
author_name: Your-Name
cloud_provider: none
contract_name: hello_world
deployment_language: typescript
ide_jetbrains: false
ide_vscode: true
preset_name: production
project_name: wakanda
python_linter: none
use_dispenser: true
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true
=======
_commit: 0.9.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: your@email.tld
author_name: Your-Name
cloud_provider: netlify
ide_jetbrains: false
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: frontend
use_daisy_ui: true
use_eslint_prettier: true
use_github_actions: false
use_jest: true
use_playwright: true
use_tailwind: true
>>>>>>> 5b82aebd4d3e7247d2d403c62f6250a432f322e7

